name: Compilazione

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice sorgente
        uses: actions/checkout@v7
      - name: Configura Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - name: Verifica Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Compila ed esegui i test
        run: ./gradlew build
